import type { AdminDashboardData } from './types';

export const demoData: AdminDashboardData = {
  kpis: [
    { label: 'Monthly revenue', value: '$48.2K', trend: '+14.8%' },
    { label: 'Open orders', value: '186', trend: '+22 today' },
    { label: 'Low stock SKUs', value: '12', trend: 'needs review' },
    { label: 'Active customers', value: '2,418', trend: '+7.4%' },
  ],
  revenueSeries: [
    { month: 'Jan', revenue: 28000 },
    { month: 'Feb', revenue: 34000 },
    { month: 'Mar', revenue: 31000 },
    { month: 'Apr', revenue: 42000 },
    { month: 'May', revenue: 48200 },
  ],
  categories: [
    { id: 1, name: 'Electronics', slug: 'electronics', description: 'Devices and accessories', active: true },
    { id: 2, name: 'Audio', slug: 'audio', description: 'Audio gear', active: true },
    { id: 3, name: 'Office', slug: 'office', description: 'Workspace equipment', active: true },
  ],
  products: [
    {
      id: 1,
      sku: 'CC-KB-001',
      name: 'Mechanical Keyboard',
      description: 'Compact keyboard for office setups',
      price: 49.9,
      stockQuantity: 18,
      lowStockThreshold: 5,
      active: true,
      categoryId: 1,
      categoryName: 'Electronics',
    },
    {
      id: 2,
      sku: 'CC-HD-014',
      name: 'Studio Headphones',
      description: 'Closed-back headphones for focused work',
      price: 89.5,
      stockQuantity: 4,
      lowStockThreshold: 8,
      active: true,
      categoryId: 2,
      categoryName: 'Audio',
    },
    {
      id: 3,
      sku: 'CC-CH-220',
      name: 'Ergonomic Chair',
      description: 'Adjustable office chair',
      price: 249.9,
      stockQuantity: 9,
      lowStockThreshold: 4,
      active: true,
      categoryId: 3,
      categoryName: 'Office',
    },
  ],
  orders: [
    {
      id: 1,
      orderNumber: 'ORD-8421',
      status: 'PAID',
      totalAmount: 249.9,
      customerId: 1,
      customerName: 'Aylin Demir',
      items: [{ productId: 3, productName: 'Ergonomic Chair', quantity: 1, unitPrice: 249.9, lineTotal: 249.9 }],
    },
    {
      id: 2,
      orderNumber: 'ORD-8420',
      status: 'FULFILLED',
      totalAmount: 89.5,
      customerId: 2,
      customerName: 'Mert Kaya',
      items: [{ productId: 2, productName: 'Studio Headphones', quantity: 1, unitPrice: 89.5, lineTotal: 89.5 }],
    },
  ],
  customers: [
    { id: 1, firstName: 'Aylin', lastName: 'Demir', email: 'aylin@example.com', phone: '+90 555 010 1001' },
    { id: 2, firstName: 'Mert', lastName: 'Kaya', email: 'mert@example.com', phone: '+90 555 010 1002' },
    { id: 3, firstName: 'Selin', lastName: 'Aras', email: 'selin@example.com', phone: '+90 555 010 1003' },
  ],
  stockMovements: [
    { id: 1, productId: 4, productName: '4K Monitor', type: 'OUT', quantity: 3, note: 'Order fulfillment' },
    { id: 2, productId: 2, productName: 'Studio Headphones', type: 'IN', quantity: 12, note: 'Supplier restock' },
    { id: 3, productId: 1, productName: 'Mechanical Keyboard', type: 'ADJUSTMENT', quantity: -1, note: 'Inventory audit' },
  ],
};
